services:
  script:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /media/tomas/Data/:/media/tomas/Data/
      - /home/tomas/Documents/1Programming/Python/DataIntegrity/data:/home/scripter/data
      - /home/tomas/Documents/1Programming/Python/DataIntegrity/errors:/home/scripter/errors
      - /home/tomas/Documents/1Programming/Python/DataIntegrity/log:/home/scripter/log
      - /etc/localtime:/etc/localtime
    logging:
      driver: "json-file"
    environment:
      - PYTHONUNBUFFERED=1
      - FILE_PATH=/media/tomas/Data/
      - DAYS_BETWEEN=14